version: 2

project_name: vessel

dist: dist

before:
  hooks:
    - go mod tidy
    - go tool gofumpt -l -w .

builds:
  - id: vsl
    main: ./cmd/vsl
    binary: "vsl-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.appVersion={{.Version}}
      - -X main.version={{.Version}}
      - -X main.commitHash={{.ShortCommit}}
      - -X main.buildDate={{.Date}}
    flags:
      - -buildvcs=false
      - -trimpath

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: gloo-foo
    name: vsl
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{.Tag}} ({{.Date}})

    Changes in this release are documented below.

